language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
before_install:
    # Installing Arpeggio as a dependency
    - cd ..
    - pip install Jinja2
    - pip install coverage
    - pip install flake8
    - git clone --depth=1 --branch=master git://github.com/textX/Arpeggio.git
    - cd Arpeggio && python setup.py install
    - cd ../textX
install:
    - ./install-all-dev.sh
script:
    - ./runtests.sh

after_success:
    - coveralls

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
